/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as bettingSol from "./Betting.sol";
export type { bettingSol };
import type * as houseSol from "./House.sol";
export type { houseSol };
import type * as helpers from "./helpers";
export type { helpers };
export type { FlyFlutterCoin } from "./FlyFlutterCoin";
export type { OddAndEven } from "./OddAndEven";
