/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as bettingRequestQrngSol from "./Betting_requestQRNG.sol";
export type { bettingRequestQrngSol };
import type * as dummyBettingSol from "./DummyBetting.sol";
export type { dummyBettingSol };
import type * as qrngExampleSol from "./QrngExample.sol";
export type { qrngExampleSol };
import type * as typesSol from "./Types.sol";
export type { typesSol };
export type { AutomateReady } from "./AutomateReady";
export type { AutomateTaskCreator } from "./AutomateTaskCreator";
export type { CounterResolverTaskCreatorWT } from "./CounterResolverTaskCreatorWT";
