/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export declare namespace Betting {
  export type BetStruct = {
    playerAddress: PromiseOrValue<string>;
    playerHand: PromiseOrValue<BigNumberish>;
    playerGuess: PromiseOrValue<BigNumberish>;
    betAmount: PromiseOrValue<BigNumberish>;
    houseHand: PromiseOrValue<BigNumberish>;
    requestId: PromiseOrValue<BytesLike>;
    taskId: PromiseOrValue<BytesLike>;
    waitingFulfillment: PromiseOrValue<boolean>;
    waitingCloseBet: PromiseOrValue<boolean>;
    winner: PromiseOrValue<string>;
  };

  export type BetStructOutput = [
    string,
    number,
    number,
    number,
    number,
    string,
    string,
    boolean,
    boolean,
    string
  ] & {
    playerAddress: string;
    playerHand: number;
    playerGuess: number;
    betAmount: number;
    houseHand: number;
    requestId: string;
    taskId: string;
    waitingFulfillment: boolean;
    waitingCloseBet: boolean;
    winner: string;
  };
}

export interface BettingInterface extends utils.Interface {
  functions: {
    "GUESS_EVEN()": FunctionFragment;
    "GUESS_ODD()": FunctionFragment;
    "MAX_FFC_BET()": FunctionFragment;
    "MAX_HAND()": FunctionFragment;
    "MIN_FFC_BET()": FunctionFragment;
    "MIN_HAND()": FunctionFragment;
    "airnode()": FunctionFragment;
    "airnodeRrp()": FunctionFragment;
    "automate()": FunctionFragment;
    "betFee()": FunctionFragment;
    "betIDsPerPlayer(address,uint256)": FunctionFragment;
    "bets(bytes32)": FunctionFragment;
    "checker(bytes32)": FunctionFragment;
    "dedicatedMsgSender()": FunctionFragment;
    "endpointIdUint256()": FunctionFragment;
    "flyFlutterCoinContract()": FunctionFragment;
    "fulfillUint256(bytes32,bytes)": FunctionFragment;
    "fundsOwner()": FunctionFragment;
    "getBetsPerPlayer(address,uint256)": FunctionFragment;
    "houseContract()": FunctionFragment;
    "oddsAndEvenContract()": FunctionFragment;
    "owner()": FunctionFragment;
    "perfomTask(bytes32)": FunctionFragment;
    "placeBet(uint8,uint8,uint8)": FunctionFragment;
    "qrngFee()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "setFees(uint256,uint256)": FunctionFragment;
    "setFlyFlutterCoinContract(address)": FunctionFragment;
    "setHouseContract(address)": FunctionFragment;
    "setOddsAndEvenContract(address)": FunctionFragment;
    "setRequestParameters(address,bytes32,address)": FunctionFragment;
    "sponsorWallet()": FunctionFragment;
    "taskTreasury()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "withdrawFunds()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "GUESS_EVEN"
      | "GUESS_ODD"
      | "MAX_FFC_BET"
      | "MAX_HAND"
      | "MIN_FFC_BET"
      | "MIN_HAND"
      | "airnode"
      | "airnodeRrp"
      | "automate"
      | "betFee"
      | "betIDsPerPlayer"
      | "bets"
      | "checker"
      | "dedicatedMsgSender"
      | "endpointIdUint256"
      | "flyFlutterCoinContract"
      | "fulfillUint256"
      | "fundsOwner"
      | "getBetsPerPlayer"
      | "houseContract"
      | "oddsAndEvenContract"
      | "owner"
      | "perfomTask"
      | "placeBet"
      | "qrngFee"
      | "renounceOwnership"
      | "setFees"
      | "setFlyFlutterCoinContract"
      | "setHouseContract"
      | "setOddsAndEvenContract"
      | "setRequestParameters"
      | "sponsorWallet"
      | "taskTreasury"
      | "transferOwnership"
      | "withdrawFunds"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "GUESS_EVEN",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "GUESS_ODD", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "MAX_FFC_BET",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "MAX_HAND", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "MIN_FFC_BET",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "MIN_HAND", values?: undefined): string;
  encodeFunctionData(functionFragment: "airnode", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "airnodeRrp",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "automate", values?: undefined): string;
  encodeFunctionData(functionFragment: "betFee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "betIDsPerPlayer",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "bets",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "checker",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "dedicatedMsgSender",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "endpointIdUint256",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "flyFlutterCoinContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "fulfillUint256",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "fundsOwner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBetsPerPlayer",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "houseContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "oddsAndEvenContract",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "perfomTask",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "placeBet",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(functionFragment: "qrngFee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setFees",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setFlyFlutterCoinContract",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setHouseContract",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setOddsAndEvenContract",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setRequestParameters",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "sponsorWallet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "taskTreasury",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFunds",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "GUESS_EVEN", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "GUESS_ODD", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "MAX_FFC_BET",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "MAX_HAND", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "MIN_FFC_BET",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "MIN_HAND", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "airnode", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "airnodeRrp", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "automate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "betFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "betIDsPerPlayer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "bets", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "checker", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "dedicatedMsgSender",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "endpointIdUint256",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "flyFlutterCoinContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fulfillUint256",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fundsOwner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getBetsPerPlayer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "houseContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "oddsAndEvenContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "perfomTask", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "placeBet", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "qrngFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setFees", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setFlyFlutterCoinContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setHouseContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setOddsAndEvenContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRequestParameters",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sponsorWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "taskTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFunds",
    data: BytesLike
  ): Result;

  events: {
    "BetPlaced(bytes32,address,uint8,uint8,uint8)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "ReceivedUint256(bytes32,uint8)": EventFragment;
    "RequestedUint256(bytes32)": EventFragment;
    "TaskCreated(bytes32)": EventFragment;
    "TaskExecuted(bytes32,string)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "BetPlaced"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ReceivedUint256"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RequestedUint256"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TaskCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TaskExecuted"): EventFragment;
}

export interface BetPlacedEventObject {
  requestId: string;
  player: string;
  playerHand: number;
  playerGuess: number;
  betAmount: number;
}
export type BetPlacedEvent = TypedEvent<
  [string, string, number, number, number],
  BetPlacedEventObject
>;

export type BetPlacedEventFilter = TypedEventFilter<BetPlacedEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface ReceivedUint256EventObject {
  requestId: string;
  houseHand: number;
}
export type ReceivedUint256Event = TypedEvent<
  [string, number],
  ReceivedUint256EventObject
>;

export type ReceivedUint256EventFilter = TypedEventFilter<ReceivedUint256Event>;

export interface RequestedUint256EventObject {
  requestId: string;
}
export type RequestedUint256Event = TypedEvent<
  [string],
  RequestedUint256EventObject
>;

export type RequestedUint256EventFilter =
  TypedEventFilter<RequestedUint256Event>;

export interface TaskCreatedEventObject {
  requestId: string;
}
export type TaskCreatedEvent = TypedEvent<[string], TaskCreatedEventObject>;

export type TaskCreatedEventFilter = TypedEventFilter<TaskCreatedEvent>;

export interface TaskExecutedEventObject {
  requestId: string;
  winner: string;
}
export type TaskExecutedEvent = TypedEvent<
  [string, string],
  TaskExecutedEventObject
>;

export type TaskExecutedEventFilter = TypedEventFilter<TaskExecutedEvent>;

export interface Betting extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: BettingInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    GUESS_EVEN(overrides?: CallOverrides): Promise<[BigNumber]>;

    GUESS_ODD(overrides?: CallOverrides): Promise<[BigNumber]>;

    MAX_FFC_BET(overrides?: CallOverrides): Promise<[BigNumber]>;

    MAX_HAND(overrides?: CallOverrides): Promise<[BigNumber]>;

    MIN_FFC_BET(overrides?: CallOverrides): Promise<[BigNumber]>;

    MIN_HAND(overrides?: CallOverrides): Promise<[BigNumber]>;

    airnode(overrides?: CallOverrides): Promise<[string]>;

    airnodeRrp(overrides?: CallOverrides): Promise<[string]>;

    automate(overrides?: CallOverrides): Promise<[string]>;

    betFee(overrides?: CallOverrides): Promise<[BigNumber]>;

    betIDsPerPlayer(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    bets(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<
      [
        string,
        number,
        number,
        number,
        number,
        string,
        string,
        boolean,
        boolean,
        string
      ] & {
        playerAddress: string;
        playerHand: number;
        playerGuess: number;
        betAmount: number;
        houseHand: number;
        requestId: string;
        taskId: string;
        waitingFulfillment: boolean;
        waitingCloseBet: boolean;
        winner: string;
      }
    >;

    checker(
      requestId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[boolean, string] & { canExec: boolean; execPayload: string }>;

    dedicatedMsgSender(overrides?: CallOverrides): Promise<[string]>;

    endpointIdUint256(overrides?: CallOverrides): Promise<[string]>;

    flyFlutterCoinContract(overrides?: CallOverrides): Promise<[string]>;

    fulfillUint256(
      requestId: PromiseOrValue<BytesLike>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    fundsOwner(overrides?: CallOverrides): Promise<[string]>;

    getBetsPerPlayer(
      player: PromiseOrValue<string>,
      endIndex: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[Betting.BetStructOutput[]]>;

    houseContract(overrides?: CallOverrides): Promise<[string]>;

    oddsAndEvenContract(overrides?: CallOverrides): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    perfomTask(
      requestId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    placeBet(
      playerHand: PromiseOrValue<BigNumberish>,
      playerGuess: PromiseOrValue<BigNumberish>,
      betAmount: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    qrngFee(overrides?: CallOverrides): Promise<[BigNumber]>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setFees(
      _betFee: PromiseOrValue<BigNumberish>,
      _qrngFee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setFlyFlutterCoinContract(
      _flyFlutterCoinContract: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setHouseContract(
      _houseContract: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setOddsAndEvenContract(
      _oddsAndEvenContract: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setRequestParameters(
      _airnode: PromiseOrValue<string>,
      _endpointIdUint256: PromiseOrValue<BytesLike>,
      _sponsorWallet: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    sponsorWallet(overrides?: CallOverrides): Promise<[string]>;

    taskTreasury(overrides?: CallOverrides): Promise<[string]>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    withdrawFunds(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  GUESS_EVEN(overrides?: CallOverrides): Promise<BigNumber>;

  GUESS_ODD(overrides?: CallOverrides): Promise<BigNumber>;

  MAX_FFC_BET(overrides?: CallOverrides): Promise<BigNumber>;

  MAX_HAND(overrides?: CallOverrides): Promise<BigNumber>;

  MIN_FFC_BET(overrides?: CallOverrides): Promise<BigNumber>;

  MIN_HAND(overrides?: CallOverrides): Promise<BigNumber>;

  airnode(overrides?: CallOverrides): Promise<string>;

  airnodeRrp(overrides?: CallOverrides): Promise<string>;

  automate(overrides?: CallOverrides): Promise<string>;

  betFee(overrides?: CallOverrides): Promise<BigNumber>;

  betIDsPerPlayer(
    arg0: PromiseOrValue<string>,
    arg1: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  bets(
    arg0: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<
    [
      string,
      number,
      number,
      number,
      number,
      string,
      string,
      boolean,
      boolean,
      string
    ] & {
      playerAddress: string;
      playerHand: number;
      playerGuess: number;
      betAmount: number;
      houseHand: number;
      requestId: string;
      taskId: string;
      waitingFulfillment: boolean;
      waitingCloseBet: boolean;
      winner: string;
    }
  >;

  checker(
    requestId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<[boolean, string] & { canExec: boolean; execPayload: string }>;

  dedicatedMsgSender(overrides?: CallOverrides): Promise<string>;

  endpointIdUint256(overrides?: CallOverrides): Promise<string>;

  flyFlutterCoinContract(overrides?: CallOverrides): Promise<string>;

  fulfillUint256(
    requestId: PromiseOrValue<BytesLike>,
    data: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  fundsOwner(overrides?: CallOverrides): Promise<string>;

  getBetsPerPlayer(
    player: PromiseOrValue<string>,
    endIndex: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<Betting.BetStructOutput[]>;

  houseContract(overrides?: CallOverrides): Promise<string>;

  oddsAndEvenContract(overrides?: CallOverrides): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  perfomTask(
    requestId: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  placeBet(
    playerHand: PromiseOrValue<BigNumberish>,
    playerGuess: PromiseOrValue<BigNumberish>,
    betAmount: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  qrngFee(overrides?: CallOverrides): Promise<BigNumber>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setFees(
    _betFee: PromiseOrValue<BigNumberish>,
    _qrngFee: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setFlyFlutterCoinContract(
    _flyFlutterCoinContract: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setHouseContract(
    _houseContract: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setOddsAndEvenContract(
    _oddsAndEvenContract: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setRequestParameters(
    _airnode: PromiseOrValue<string>,
    _endpointIdUint256: PromiseOrValue<BytesLike>,
    _sponsorWallet: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  sponsorWallet(overrides?: CallOverrides): Promise<string>;

  taskTreasury(overrides?: CallOverrides): Promise<string>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  withdrawFunds(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    GUESS_EVEN(overrides?: CallOverrides): Promise<BigNumber>;

    GUESS_ODD(overrides?: CallOverrides): Promise<BigNumber>;

    MAX_FFC_BET(overrides?: CallOverrides): Promise<BigNumber>;

    MAX_HAND(overrides?: CallOverrides): Promise<BigNumber>;

    MIN_FFC_BET(overrides?: CallOverrides): Promise<BigNumber>;

    MIN_HAND(overrides?: CallOverrides): Promise<BigNumber>;

    airnode(overrides?: CallOverrides): Promise<string>;

    airnodeRrp(overrides?: CallOverrides): Promise<string>;

    automate(overrides?: CallOverrides): Promise<string>;

    betFee(overrides?: CallOverrides): Promise<BigNumber>;

    betIDsPerPlayer(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    bets(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<
      [
        string,
        number,
        number,
        number,
        number,
        string,
        string,
        boolean,
        boolean,
        string
      ] & {
        playerAddress: string;
        playerHand: number;
        playerGuess: number;
        betAmount: number;
        houseHand: number;
        requestId: string;
        taskId: string;
        waitingFulfillment: boolean;
        waitingCloseBet: boolean;
        winner: string;
      }
    >;

    checker(
      requestId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[boolean, string] & { canExec: boolean; execPayload: string }>;

    dedicatedMsgSender(overrides?: CallOverrides): Promise<string>;

    endpointIdUint256(overrides?: CallOverrides): Promise<string>;

    flyFlutterCoinContract(overrides?: CallOverrides): Promise<string>;

    fulfillUint256(
      requestId: PromiseOrValue<BytesLike>,
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    fundsOwner(overrides?: CallOverrides): Promise<string>;

    getBetsPerPlayer(
      player: PromiseOrValue<string>,
      endIndex: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<Betting.BetStructOutput[]>;

    houseContract(overrides?: CallOverrides): Promise<string>;

    oddsAndEvenContract(overrides?: CallOverrides): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    perfomTask(
      requestId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    placeBet(
      playerHand: PromiseOrValue<BigNumberish>,
      playerGuess: PromiseOrValue<BigNumberish>,
      betAmount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean, Betting.BetStructOutput]>;

    qrngFee(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    setFees(
      _betFee: PromiseOrValue<BigNumberish>,
      _qrngFee: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setFlyFlutterCoinContract(
      _flyFlutterCoinContract: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setHouseContract(
      _houseContract: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setOddsAndEvenContract(
      _oddsAndEvenContract: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setRequestParameters(
      _airnode: PromiseOrValue<string>,
      _endpointIdUint256: PromiseOrValue<BytesLike>,
      _sponsorWallet: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    sponsorWallet(overrides?: CallOverrides): Promise<string>;

    taskTreasury(overrides?: CallOverrides): Promise<string>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawFunds(overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "BetPlaced(bytes32,address,uint8,uint8,uint8)"(
      requestId?: PromiseOrValue<BytesLike> | null,
      player?: PromiseOrValue<string> | null,
      playerHand?: null,
      playerGuess?: null,
      betAmount?: null
    ): BetPlacedEventFilter;
    BetPlaced(
      requestId?: PromiseOrValue<BytesLike> | null,
      player?: PromiseOrValue<string> | null,
      playerHand?: null,
      playerGuess?: null,
      betAmount?: null
    ): BetPlacedEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;

    "ReceivedUint256(bytes32,uint8)"(
      requestId?: PromiseOrValue<BytesLike> | null,
      houseHand?: PromiseOrValue<BigNumberish> | null
    ): ReceivedUint256EventFilter;
    ReceivedUint256(
      requestId?: PromiseOrValue<BytesLike> | null,
      houseHand?: PromiseOrValue<BigNumberish> | null
    ): ReceivedUint256EventFilter;

    "RequestedUint256(bytes32)"(
      requestId?: PromiseOrValue<BytesLike> | null
    ): RequestedUint256EventFilter;
    RequestedUint256(
      requestId?: PromiseOrValue<BytesLike> | null
    ): RequestedUint256EventFilter;

    "TaskCreated(bytes32)"(
      requestId?: PromiseOrValue<BytesLike> | null
    ): TaskCreatedEventFilter;
    TaskCreated(
      requestId?: PromiseOrValue<BytesLike> | null
    ): TaskCreatedEventFilter;

    "TaskExecuted(bytes32,string)"(
      requestId?: PromiseOrValue<BytesLike> | null,
      winner?: PromiseOrValue<string> | null
    ): TaskExecutedEventFilter;
    TaskExecuted(
      requestId?: PromiseOrValue<BytesLike> | null,
      winner?: PromiseOrValue<string> | null
    ): TaskExecutedEventFilter;
  };

  estimateGas: {
    GUESS_EVEN(overrides?: CallOverrides): Promise<BigNumber>;

    GUESS_ODD(overrides?: CallOverrides): Promise<BigNumber>;

    MAX_FFC_BET(overrides?: CallOverrides): Promise<BigNumber>;

    MAX_HAND(overrides?: CallOverrides): Promise<BigNumber>;

    MIN_FFC_BET(overrides?: CallOverrides): Promise<BigNumber>;

    MIN_HAND(overrides?: CallOverrides): Promise<BigNumber>;

    airnode(overrides?: CallOverrides): Promise<BigNumber>;

    airnodeRrp(overrides?: CallOverrides): Promise<BigNumber>;

    automate(overrides?: CallOverrides): Promise<BigNumber>;

    betFee(overrides?: CallOverrides): Promise<BigNumber>;

    betIDsPerPlayer(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    bets(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    checker(
      requestId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    dedicatedMsgSender(overrides?: CallOverrides): Promise<BigNumber>;

    endpointIdUint256(overrides?: CallOverrides): Promise<BigNumber>;

    flyFlutterCoinContract(overrides?: CallOverrides): Promise<BigNumber>;

    fulfillUint256(
      requestId: PromiseOrValue<BytesLike>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    fundsOwner(overrides?: CallOverrides): Promise<BigNumber>;

    getBetsPerPlayer(
      player: PromiseOrValue<string>,
      endIndex: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    houseContract(overrides?: CallOverrides): Promise<BigNumber>;

    oddsAndEvenContract(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    perfomTask(
      requestId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    placeBet(
      playerHand: PromiseOrValue<BigNumberish>,
      playerGuess: PromiseOrValue<BigNumberish>,
      betAmount: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    qrngFee(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setFees(
      _betFee: PromiseOrValue<BigNumberish>,
      _qrngFee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setFlyFlutterCoinContract(
      _flyFlutterCoinContract: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setHouseContract(
      _houseContract: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setOddsAndEvenContract(
      _oddsAndEvenContract: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setRequestParameters(
      _airnode: PromiseOrValue<string>,
      _endpointIdUint256: PromiseOrValue<BytesLike>,
      _sponsorWallet: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    sponsorWallet(overrides?: CallOverrides): Promise<BigNumber>;

    taskTreasury(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    withdrawFunds(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    GUESS_EVEN(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    GUESS_ODD(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    MAX_FFC_BET(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    MAX_HAND(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    MIN_FFC_BET(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    MIN_HAND(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    airnode(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    airnodeRrp(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    automate(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    betFee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    betIDsPerPlayer(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    bets(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    checker(
      requestId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    dedicatedMsgSender(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    endpointIdUint256(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    flyFlutterCoinContract(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    fulfillUint256(
      requestId: PromiseOrValue<BytesLike>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    fundsOwner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getBetsPerPlayer(
      player: PromiseOrValue<string>,
      endIndex: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    houseContract(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    oddsAndEvenContract(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    perfomTask(
      requestId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    placeBet(
      playerHand: PromiseOrValue<BigNumberish>,
      playerGuess: PromiseOrValue<BigNumberish>,
      betAmount: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    qrngFee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setFees(
      _betFee: PromiseOrValue<BigNumberish>,
      _qrngFee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setFlyFlutterCoinContract(
      _flyFlutterCoinContract: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setHouseContract(
      _houseContract: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setOddsAndEvenContract(
      _oddsAndEvenContract: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setRequestParameters(
      _airnode: PromiseOrValue<string>,
      _endpointIdUint256: PromiseOrValue<BytesLike>,
      _sponsorWallet: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    sponsorWallet(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    taskTreasury(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    withdrawFunds(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
