/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  FlyFlutterCoin,
  FlyFlutterCoinInterface,
} from "../../../contracts/Betting.sol/FlyFlutterCoin";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "transferFrom",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class FlyFlutterCoin__factory {
  static readonly abi = _abi;
  static createInterface(): FlyFlutterCoinInterface {
    return new utils.Interface(_abi) as FlyFlutterCoinInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): FlyFlutterCoin {
    return new Contract(address, _abi, signerOrProvider) as FlyFlutterCoin;
  }
}
