/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  HouseContract,
  HouseContractInterface,
} from "../../../contracts/Betting.sol/HouseContract";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "receiveBet",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "sendBet",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class HouseContract__factory {
  static readonly abi = _abi;
  static createInterface(): HouseContractInterface {
    return new utils.Interface(_abi) as HouseContractInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): HouseContract {
    return new Contract(address, _abi, signerOrProvider) as HouseContract;
  }
}
