/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { DummyBetting__factory } from "./DummyBetting__factory";
export { IHouse__factory } from "./IHouse__factory";
